import { showModal, hideModal, closeAllModals, closeTopModal, toggleModal } from './modalManager';
import type { ModelData, PinData } from '../types';

export const modalService = {
  showRecordDetails:  (record: PinData)   => showModal('record-details', { record }),
  hideRecordDetails:  ()                  => hideModal('record-details'),
  showModelDetails:   (model: ModelData)  => showModal('model-details', { model }),
  hideModelDetails:   ()                  => hideModal('model-details'),
  showModelEditor:    (editMode = false, modelData?: ModelData) => showModal('model-editor', { editMode, modelData }),
  hideModelEditor:    ()                  => hideModal('model-editor'),
  showBrainstorming:  ()                  => showModal('brainstorming'),
  hideBrainstorming:  ()                  => hideModal('brainstorming'),
  showSimulation:     ()                  => showModal('simulation'),
  hideSimulation:     ()                  => hideModal('simulation'),
  showActionEvent:    ()                  => showModal('action-event'),
  hideActionEvent:    ()                  => hideModal('action-event'),
  showPetition:       ()                  => showModal('petition'),
  hidePetition:       ()                  => hideModal('petition'),
  showCrowdfunding:   ()                  => showModal('crowdfunding'),
  hideCrowdfunding:   ()                  => hideModal('crowdfunding'),
  showGigEconomy:     ()                  => showModal('gig-economy'),
  hideGigEconomy:     ()                  => hideModal('gig-economy'),
  showCoordinatePicker: ()                => showModal('coordinate-picker'),
  hideCoordinatePicker: ()                => hideModal('coordinate-picker'),
  showZoomRequired:   ()                  => showModal('zoom-required'),
  hideZoomRequired:   ()                  => hideModal('zoom-required'),
  closeAllModals,
  closeTopModal,
  toggleModal,
};
